apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud
  labels:
    app: fraud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud
  template:
    metadata:
      name: fraud
      labels:
        app: fraud
    spec:
      containers:
        - name: fraud
          image: moxanes/fraud:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: client-kube
            - name: SPRING_DATASOURCE_HOST
              value: postgres
            - name: SPRING_DATASOURCE_USERNAME
              value: anescode
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
            - name: SPRING_RABBITMQ_ADDRESSES
              value: rabbitmq:5672
            - name: SPRING_ZIPKIN_BASE_URL
              value: http://zipkin:9411
      restartPolicy: Always
      